#записываем рекордером и пробуем воспроизвести

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestUntitled():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout = 2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_untitled(self):
        self.driver.get("https://www.ukr.net/")
        self.driver.set_window_size(1206, 871)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.ID, "id-input-login").click()
        self.driver.find_element(By.ID, "id-input-login").send_keys("user")
        self.driver.find_element(By.ID, "id-input-password").send_keys("pass")
        self.driver.find_element(By.CSS_SELECTOR, ".form__submit").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "Вхідні").click()
        self.vars["win4699"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win4699"])
        self.driver.find_element(By.LINK_TEXT, "Написати листа").click()
        self.driver.find_element(By.ID, "toField").send_keys("pgir@mail.ua")
        self.driver.find_element(By.NAME, "subject").send_keys("test")
        element = self.driver.find_element(By.CSS_SELECTOR, ".fmedit > div:nth-child(2)")
        self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'test3'}", element)
        self.driver.find_element(By.CSS_SELECTOR, ".upl-fake-button > input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".send-button:nth-child(1) > input").click()

